springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# KeyCloak
keycloak:
  enabled: true
  disable-trust-manager: true
  auth-server-url: http://10.110.22.13/auth
  realm: picp
  public-client: false
  credentials:
    secret: 060ae88a-bb7c-4fec-abdd-3c482cc184ac
  resource: bss-server
  ssl-required: none
  bearer-only: true
  cors: true
  cors-max-age: 1728000
  cors-allowed-headers: Authorization, Origin, X-Requested-With, Content-Type, X-Custom-Header
  cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS

# Logback
logging:
  config: classpath:logback-dev.xml

http:
  #最大连接数
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  statleConnectionCheckEnabled: true