# Mysql
spring:
  resources:
    # Swagger
    add-mappings: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://10.110.10.21:3306/icptest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update