# Mysql
spring:
  resources:
    # Swagger
    add-mappings: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://10.110.1.26:3306/icp_eip?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: eip
      password: eip0914
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# KeyCloak
keycloak:
  enabled: true
  disable-trust-manager: true
  auth-server-url: http://10.110.22.13:8888/auth
  realm: picp
  public-client: false
  credentials:
    secret: 060ae88a-bb7c-4fec-abdd-3c482cc184ac
  resource: bss-server
  ssl-required: none

# Logback
logging:
  config: classpath:logback-dev.xml

http:
  #最大连接数
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  statleConnectionCheckEnabled: true