# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 400
    max-threads: 300

  port: 8080
  servlet:
    context-path: /eip
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

error:
  code: 106

 #KeyCloak
keycloak:
  enabled: true
  disable-trust-manager: true
  auth-server-url: https://iopdev.10.110.25.123.xip.io/auth
  realm: picp
  public-client: false
  credentials:
    secret: 3da8fb1c-97d7-4627-8c4c-b002942e820f
  resource: iaas-server
  ssl-required: none
  bearer-only: true
  cors: true
  cors-max-age: 1728000
  cors-allowed-headers: Authorization, Origin, X-Requested-With, Content-Type, X-Custom-Header
  cors-allowed-methods: POST,PUT,DELETE,GET,OPTIONS,PATCH


# Logback
logging:
  config: classpath:log4j.properties

http:
  #最大连接数
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 10000
  connectionRequestTimeout: 5000
  socketTimeout: 100000
  statleConnectionCheckEnabled: true


webSocket:   http://service.10.110.25.123.xip.io/websocket/v1/messages

blackList: /health-status

# Mysql
# 环境 dev|prod
spring:
  profiles:
    active: prod
  resources:
    # Swagger
    add-mappings: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://10.110.1.26:3306/icp_eip?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: eip
      password: eip0914
      initialSize: 5
      minIdle: 3
      maxActive: 200
      maxWait: 60000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /dbstructapi
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    contexts: dev

    #Rabbit mq common config
  rabbitmq:
    host: 10.110.25.74
    port: 20908
    username: guest
    password: 123456aB
    #    Matchting with dead letter queue can avoid blocking of business queue message.
    listener:
      simple:
        default-requeue-rejected: false
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  # Asia/Shanghai  UTC ...
    time-zone: GMT
  #true false
    serialization:
      write-dates-as-timestamps: false


# IAM
iam:
  #url: http://service.inspurtest.com/auth
#  测试/staging/生产 配置
  url: http://iam-apiserver.iam.svc.cluster.local:9101/auth
#  url: http://service.inspurtest.com/auth
  ladon:
    #url: http://10.110.25.71:48156/auth
#  测试/staging/生产 配置
    url: http://iam-auth-ladon.iam.svc.cluster.local:8090/auth
#    url: http://10.110.25.71:48156/auth

common:
  region: cn-north-3
resttemplate:
  header: Attributes
  cookie: realm_roles,username
  referer: https://console1.cloud.inspur.com/
#rabbit mq queues config
bss:
  queues:
    order:
      name:
        eip: queue.eip.order
        sbw: queue.sbw.order
        ipts: queue.ipts.order
      messageTTL: 300000
      binding:
        exchange: exchange.region
        routingKey:
          eip: key.eip.order
          sbw: key.sbw.order
          ipts: key.ipts.order
        returnRoutingKey: key.return.order
        returnFlowRoutingKey: key.return.bill
      deadLetterExchange: exchange.dlx
      deadLetterRoutingKey: key.dlx
    change:
      name:
        eip: queue.eip.change
        sbw: queue.sbw.change
        ipts: queue.ipts.change
      messageTTL: 300000
      binding:
        exchange: exchange.region
        routingKey:
          eip: key.eip.change
          sbw: key.sbw.change
          ipts: key.ipts.change
        returnRoutingKey: key.return.change
      deadLetterExchange: exchange.dlx
      deadLetterRoutingKey: key.dlx



slbUrl: http://cn-north-3.10.110.25.123.xip.io/slb/v1/servers/

##administrator rights
#openstackIp: 10.110.28.35
#openstackUrl: https://10.110.28.35:5000/v3
#userNameS: admineip
#passwordS: eip1qaz2wsx
#projectIdS: f9ba41b61a6146c1a392815ea088c437
#userDomainIdS: default
#debugRegionS: inspurtest

openstack:
  authUrl: https://10.110.28.35:5000/v3
  authRegion: inspurtest
  domain: Default
  interfaceType: admin
  username: admineip
  password: eip1qaz2wsx
  projectName: admineip

#Firewall configuration
firewall:
  type: hillstone
  id: 3f26960e-6ac3-4636-aae7-822ef3579288
  ip: 10.110.29.206
  port: 443
  user: iojHL/UrEMTtZ3Ec3YtV1/0NdjZmNE14
  password: dNe9QCSE9S8AgSEshlpAXsklH8yW0vlE
#  硬件设备插网线的端口
  interface: 6

#Flpnetwork configuration
fipNetworkId: f4790efe-5df0-4f04-991b-a3c105e63b71


Kafka:
  servers: 10.110.25.107:9092,10.10.6.6:9092,10.110.25.105:9092
  topic: monitor-metrics

regionCode: cn-north-3
scheduleTime: 0 0/5 * * * ?
minEipNum: 0


