# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /eip
# 环境 dev|prod
spring:
  profiles:
    active: dev


bssURL:
  ignoSSL: true
  submitPay: http://117.73.2.105:8086/order/submitpay #  //1.2.8 订单接口POST
  quotaUrl:    http://117.73.2.105:8083/crm/quota #//1.2.11	查询用户配额的接口
  returnMq:    http://commonatomapi.devops.inspur.com/common/productreturn
  webSocket:   http://tenantconservice.devops.inspur.com/console/websocket/sendMessage
  eipAtom:     http://eip-atom.cn-north-3.devops.inspur.com/eip/v2.0/eips/
